services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
      - next_volume:/app/.next
      - ./frontend/.env.local:/app/.env.local
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - SUPABASE_URL=http://supabase_kong_cv-match:8000
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000,http://127.0.0.1:3000
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network
      - supabase_network_cv-match

networks:
  app-network:
    driver: bridge
  supabase_network_cv-match:
    external: true

volumes:
  node_modules_volume:
  next_volume:
