version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_volume:/app/node_modules
      - next_volume:/app/.next
      - ./frontend/.env.local:/app/.env.local
    user: "1001:1001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    user: "1000:1000"
    environment:
      - ENVIRONMENT=development
      - SUPABASE_URL=http://supabase_kong_cv-match:8000
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000,http://127.0.0.1:3000
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1
    networks:
      - app-network
      - supabase_network_cv-match
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
  supabase_network_cv-match:
    external: true

volumes:
  node_modules_volume:
  next_volume:
