global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cv-match.local'
  smtp_require_tls: false

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        service: monitoring
      receiver: 'monitoring-alerts'
      group_wait: 5s
      repeat_interval: 30m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/critical'
    email_configs:
      - to: 'admin@cv-match.local'
        headers:
          subject: '[CRITICAL] CV-Match Alert: {{ .GroupLabels.alertname }}'
        html: |
          {{ range .Alerts }}
          <h2>Alert: {{ .Annotations.summary }}</h2>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Labels:</strong> {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}</p>
          <hr>
          {{ end }}

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/warning'
    email_configs:
      - to: 'ops@cv-match.local'
        headers:
          subject: '[WARNING] CV-Match Alert: {{ .GroupLabels.alertname }}'
        html: |
          {{ range .Alerts }}
          <h2>Alert: {{ .Annotations.summary }}</h2>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Labels:</strong> {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}</p>
          <hr>
          {{ end }}

  - name: 'monitoring-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/monitoring'
    email_configs:
      - to: 'devops@cv-match.local'
        headers:
          subject: '[MONITORING] CV-Match Alert: {{ .GroupLabels.alertname }}'
        html: |
          {{ range .Alerts }}
          <h2>Alert: {{ .Annotations.summary }}</h2>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Labels:</strong> {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}</p>
          <hr>
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

  - source_match:
      service: 'monitoring'
    target_match:
      service: 'docker'
    equal: ['instance']