groups:
  - name: docker_container_alerts
    rules:
      # High CPU usage alerts
      - alert: ContainerHighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "High CPU usage on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is above 80% for more than 5 minutes. Current value: {{ $value }}%"

      - alert: ContainerCriticalCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: docker
        annotations:
          summary: "Critical CPU usage on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} CPU usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"

      # Memory usage alerts
      - alert: ContainerHighMemoryUsage
        expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""}) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "High memory usage on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} memory usage is above 85% for more than 5 minutes. Current value: {{ $value }}%"

      - alert: ContainerCriticalMemoryUsage
        expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""}) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: docker
        annotations:
          summary: "Critical memory usage on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} memory usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"

      # Container restart alerts
      - alert: ContainerRestarting
        expr: increase(container_start_time_seconds{name!=""}[1h]) > 3
        for: 0m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container {{ $labels.name }} is restarting frequently"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last hour"

      # Container health check failures
      - alert: ContainerUnhealthy
        expr: container_health_status{name!=""} != 1
        for: 2m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container {{ $labels.name }} is unhealthy"
          description: "Container {{ $labels.name }} health check has been failing for more than 2 minutes"

      # Disk I/O alerts
      - alert: ContainerHighDiskIO
        expr: rate(container_fs_reads_bytes_total{name!=""}[5m]) + rate(container_fs_writes_bytes_total{name!=""}[5m]) > 10485760
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "High disk I/O on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} disk I/O is above 10MB/s for more than 5 minutes. Current value: {{ $value }}B/s"

      # Network I/O alerts
      - alert: ContainerHighNetworkIO
        expr: rate(container_network_receive_bytes_total{name!=""}[5m]) + rate(container_network_transmit_bytes_total{name!=""}[5m]) > 10485760
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "High network I/O on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} network I/O is above 10MB/s for more than 5 minutes. Current value: {{ $value }}B/s"

  - name: system_alerts
    rules:
      # Host CPU alerts
      - alert: HostHighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage on host {{ $labels.instance }}"
          description: "Host CPU usage is above 80% for more than 5 minutes. Current value: {{ $value }}%"

      - alert: HostCriticalCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical CPU usage on host {{ $labels.instance }}"
          description: "Host CPU usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"

      # Host memory alerts
      - alert: HostHighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage on host {{ $labels.instance }}"
          description: "Host memory usage is above 85% for more than 5 minutes. Current value: {{ $value }}%"

      - alert: HostCriticalMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Critical memory usage on host {{ $labels.instance }}"
          description: "Host memory usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"

      # Host disk space alerts
      - alert: HostLowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Low disk space on host {{ $labels.instance }}"
          description: "Host disk space is below 10% on {{ $labels.mountpoint }}. Current usage: {{ $value }}%"

  - name: application_alerts
    rules:
      # Frontend application alerts
      - alert: FrontendDown
        expr: up{job="frontend"} == 0
        for: 1m
        labels:
          severity: critical
          service: frontend
        annotations:
          summary: "Frontend service is down"
          description: "Frontend service has been down for more than 1 minute"

      - alert: FrontendHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="frontend"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: frontend
        annotations:
          summary: "Frontend high response time"
          description: "Frontend 95th percentile response time is above 2 seconds for more than 5 minutes. Current value: {{ $value }}s"

      # Backend application alerts
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "Backend service is down"
          description: "Backend service has been down for more than 1 minute"

      - alert: BackendHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="backend"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "Backend high response time"
          description: "Backend 95th percentile response time is above 2 seconds for more than 5 minutes. Current value: {{ $value }}s"

      - alert: BackendHighErrorRate
        expr: rate(http_requests_total{job="backend",status=~"5.."}[5m]) / rate(http_requests_total{job="backend"}[5m]) * 100 > 5
        for: 2m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "Backend high error rate"
          description: "Backend error rate is above 5% for more than 2 minutes. Current value: {{ $value }}%"

  - name: monitoring_alerts
    rules:
      # Prometheus alerts
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
          service: monitoring
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus has been down for more than 1 minute"

      - alert: PrometheusTargetDown
        expr: up == 0
        for: 5m
        labels:
          severity: warning
          service: monitoring
        annotations:
          summary: "Prometheus target is down"
          description: "Prometheus target {{ $labels.job }} on {{ $labels.instance }} has been down for more than 5 minutes"

      # Grafana alerts
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 1m
        labels:
          severity: warning
          service: monitoring
        annotations:
          summary: "Grafana is down"
          description: "Grafana has been down for more than 1 minute"

      # cAdvisor alerts
      - alert: CadvisorDown
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: warning
          service: monitoring
        annotations:
          summary: "cAdvisor is down"
          description: "cAdvisor has been down for more than 1 minute"

      # Node Exporter alerts
      - alert: NodeExporterDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: warning
          service: monitoring
        annotations:
          summary: "Node Exporter is down"
          description: "Node Exporter has been down for more than 1 minute"